### PR TITLE
Allow cross-compiling

### PR DESCRIPTION
**Pull request by qwertychouskie**
Tested on Ubuntu 18.04, `stand_alone.exe` tested in Wine.

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Thanks!

**Comment by catid** [comment]
Doesn't seem to build on MSVC anymore though - The entrypoint is now WinMain instead of main()

**Comment by catid** [comment]
Removing WIN32 from the add_executable() works for me

**Comment by qwertychouskie** [comment]
OK, wasn't sure what it really did, just saw it in the documentation for the command and thought it should be there.

**Pull request merged**
